### ISSUE TITLE
Must Have - Footer (details in comments)

### ISSUE THREAD

**Issue by KWweb** [chingu-voyage6/toucans-team-21#18]
Credit (made by) text, Link to Github source code, and disclaimer text. Link top of page on the right hand side

**Comment by ellehallal** [comment]
FOOTER:

background: #40596b

font info: 
Font - Signika
Font family stack = Signika, -apple-system, system-ui, "Segoe UI", Roboto, Helvetica, Arial, sans-serif

size - 13.2px
weight- 300
colour - #B9C2C9
hyperlinks:

text-decoration: underline
