### ISSUE TITLE
Must Have - How It Works section (details in comments)

### ISSUE THREAD

**Issue by KWweb** [chingu-voyage6/toucans-team-21#20]
Header, then underneath 3 cards (image/icon above text) in a row explaing what Tickybot does and how to get it (with link to Slack)

**Comment by KWweb** [comment]
Should be THIRD section

**Comment by ellehallal** [comment]
To reiterate:
- header "How It Works"
- 3 sections
- each section has an image on the top with text underneath

**Comment by ellehallal** [comment]
HOW IT WORKS:

background: #90ddaa
underscore line under the title: #b8e5fa
cards background: #40596b
cards description background: #fafafa

Font info:

Font - Signika
Font family stack = Signika, -apple-system, system-ui, "Segoe UI", Roboto, Helvetica, Arial, sans-serif

*title / headers

size - 40px
weight- 300 / 600 "Ticky:
colour - #3F3F3F
*body text

size - 20px
weight- 300 / 600 for bold text
colour - #3F3F3F
