### ISSUE TITLE
Must Have - What is Tickybot section (details in comments)

### ISSUE THREAD

**Issue by KWweb** [chingu-voyage6/toucans-team-21#21]
Heading: What Is TickyBot
Explanatory text in 2 columns underneath

**Comment by KWweb** [comment]
Should be SECOND section

**Comment by ellehallal** [comment]
Two columns on one row, with additional information in a column underneath, spanning the length of the row above

**Comment by ellehallal** [comment]
WHAT IS TICKYBOT?

background: #fafafa
underscore line under the title: #b8e5fa

Font info:

Font - Signika
Font family stack = Signika, -apple-system, system-ui, "Segoe UI", Roboto, Helvetica, Arial, sans-serif

*title / headers

size - 40px
weight- 300 / 600 "Ticky:
colour - #3F3F3F
*body text

size - 20px
weight- 300 / 600 for bold text
colour - #3F3F3F
