### ISSUE TITLE
Must Have - Start Using TickyBot Today section (details in comments)

### ISSUE THREAD

**Issue by KWweb** [chingu-voyage6/toucans-team-21#22]
Centred text and button with what looks like 2 empty columns which are slightly smaller in size either side

**Comment by ellehallal** [comment]
- header
- description text
- call to action button (Add to slack)

**Comment by ellehallal** [comment]
START USING TICKYBOT:

background: ##FAFAFA
-- underscore line under the title: #b8e5fa
call to action button background#40596b
call to action button background:hover : #4b4b4b

Font info:

Font - Signika
Font family stack = Signika, -apple-system, system-ui, "Segoe UI", Roboto, Helvetica, Arial, sans-serif

*title / headers

size - 40px
weight- 300 / 600 "Ticky:
colour - #3F3F3F
*body text

size - 20px
weight- 300 / 600 for bold text
colour - #3F3F3F
START USING TICKYBOT SECTION

*add to slack button

size - 28px
weight - 300 / 600 for "slack"
colour - #EDEDED
