### ISSUE TITLE
Must Have - 6 different sections (see comments for breakdown)

### ISSUE THREAD

**Issue by ellehallal** [chingu-voyage6/toucans-team-21#27]

**Comment by ellehallal** [comment]
From top to bottom:
- Nav bar
- Main / jumbotron (with call to action button)
- What Is Tickybot?
- How It Works
- Start Using Tickybot today (with call to action button)
- Footer

**Comment by luapuhpuh** [comment]
hex color numbers

NAV BAR:
- background: #40596b 
- links: #f3d05e
- links:hover: #eef9fd

MAIN:
- background: #55c0ec
- call to action button background: #eef9fd

WHAT IS TICKYBOT?
- background: #fafafa
- underscore line under the title: #b8e5fa

HOW IT WORKS:
- background: #90ddaa
- underscore line under the title: #b8e5fa
- cards background: #40596b
- cards description background: #fafafa

START USING TICKYBOT:
- background: ##FAFAFA
-- underscore line under the title: #b8e5fa
- call to action button background#40596b
- call to action button background:hover : #4b4b4b

FOOTER:
- background: #40596b

**Comment by ellehallal** [comment]
Font info:
- Font - Signika
- Font family stack = Signika, -apple-system, system-ui, "Segoe UI", Roboto, Helvetica, Arial, sans-serif

NAV BAR
-  size - 20px
- weight - 300
- Colour - #FFD05B
- On mouseover  - #FFFFFF

MAIN / JUMBOTRON
*Header text - "Ticky":
- size - 80px
- weight - 600
- colour  -#224D5E

*Header text - "Bot":
- size - 80px
- weight - 300
- colour -#224D5E

*tagline: 
- size - 26.8px
- weight -  300
- colour - #ffffff

*add to slack button: 
- size - 28px
- weight - 300 / 600 for "slack"  
- colour - #535758

REST OF PAGE:

*title / headers
- size - 40px
- weight-  300 / 600 "Ticky:
- colour - #3F3F3F

*body text
- size - 20px
- weight-  300 / 600 for bold text
- colour - #3F3F3F

START USING TICKYBOT SECTION

*add to slack button
- size - 28px
- weight - 300 / 600 for "slack"  
- colour - #EDEDED

FOOTER
- size - 13.2px
- weight-  300
- colour - #B9C2C9

hyperlinks:
- text-decoration: underline
