### ISSUE TITLE
Must Have - A Main / jumbotron section  (details in comments)

### ISSUE THREAD

**Issue by luapuhpuh** [chingu-voyage6/toucans-team-21#6]

**Comment by ellehallal** [comment]
From @luapuhpuh 
- short description
- tickybot logo
 - call to action button

**Comment by ellehallal** [comment]
MAIN:
background: #55c0ec
call to action button background: #eef9fd

Font info:

Font - Signika
Font family stack = Signika, -apple-system, system-ui, "Segoe UI", Roboto, Helvetica, Arial, sans-serif

MAIN / JUMBOTRON

*Header text - "Ticky":
size - 80px
weight - 600
colour -#224D5E

*Header text - "Bot":
size - 80px
weight - 300
colour -#224D5E

*tagline:
size - 26.8px
weight - 300
colour - #ffffff

*add to slack button:
size - 28px
weight - 300 / 600 for "slack"
colour - #535758
